cc_library( # 바이너리 실행규칙
    name = "hello_app",  # 타겟 이름 (Label: //main:hello_app)
    srcs = ["hello_app.cpp"], # 입력 소스 파일
    hdrs = ["hello_app.h"], # related headers
    visibility = ["//visibility:public"] # using this header at the other packages
)
